-- =============================================================
-- ICT Service Request Management System — Supabase schema
-- Run this in the Supabase SQL Editor (Project > SQL Editor).
-- =============================================================

create table if not exists service_requests (
  id              bigint generated by default as identity primary key,
  requester_name  text not null,
  department      text not null,
  category        text not null,
  description     text not null,
  priority        text not null check (priority in ('Low', 'Medium', 'High')),
  status          text not null default 'Pending'
                    check (status in ('Pending', 'In Progress', 'Completed')),
  created_at      timestamptz not null default now(),
  user_id         uuid references auth.users(id)
);

-- BR-10: prevent unauthorized modification at the database layer.
alter table service_requests enable row level security;

-- Any authenticated user can see all requests (shared ICT-office visibility).
create policy "Authenticated users can view requests"
  on service_requests
  for select
  to authenticated
  using (true);

-- A user can only insert a request tagged with their own user_id.
create policy "Authenticated users can insert requests"
  on service_requests
  for insert
  to authenticated
  with check (auth.uid() = user_id);

-- A user can only update rows they created.
create policy "Authenticated users can update requests"
  on service_requests
  for update
  to authenticated
  using (auth.uid() = user_id);

-- A user can only delete rows they created.
create policy "Authenticated users can delete requests"
  on service_requests
  for delete
  to authenticated
  using (auth.uid() = user_id);

-- Helpful index for the search feature (requester_name / description).
create index if not exists idx_service_requests_created_at
  on service_requests (created_at desc);
